repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: v1.0.0
  hooks:
  - id: dbt-compile
  - id: dbt-docs-generate
  - id: check-source-table-has-description
    files: ^models/
  - id: check-model-has-properties-file
    files: ^models/
  - id: check-model-has-all-columns
    files: ^models/
  - id: check-model-has-description
    files: ^models/
