files: ^transform/models/

repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.3

    hooks:
      - id: dbt-deps
      - id: dbt-parse
      - id: check-script-has-no-table-name
      - id: check-script-ref-and-source
      - id: check-model-has-description
      - id: check-model-has-properties-file
