default:
    target: dev
    outputs:
        dev:
            type: snowflake
            account: "toa80779"
            role: ANALYST
            user: "{{ snowflake_username }}"
            password: "{{ snowflake_password }}"
            database: BALBOA
            warehouse: TRANSFORMING_WAREHOUSE
            schema: "{{ snowflake_username }}"
            threads: 8
            keepalives_idle: 0
