# For more information on this file, visit https://github.com/datacoves/dbt-coves

generate:
  sources:
    database: RAW
    schemas:
      - RAW

extract:
  airbyte:
    path: /config/workspace/load
    host: http://airbyte-server
    port: 8001
    dbt_list_args: --exclude source:dbt_artifacts
