- name: '"COVID19_EPIDEMIOLOGICAL_DATA"."PUBLIC"."JHU_COVID_19"'
  columns:
    COUNTRY_REGION: VARCHAR(16777216)
    PROVINCE_STATE: VARCHAR(16777216)
    COUNTY: VARCHAR(16777216)
    FIPS: VARCHAR(16777216)
    DATE: DATE
    CASE_TYPE: VARCHAR(16777216)
    CASES: DECIMAL(38, 0)
    LONG: FLOAT
    LAT: FLOAT
    ISO3166_1: VARCHAR(16777216)
    ISO3166_2: VARCHAR(16777216)
    DIFFERENCE: DECIMAL(38, 0)
    LAST_UPDATED_DATE: TIMESTAMPNTZ(9)
    LAST_REPORTED_FLAG: BOOLEAN
- name: '"RAW"."GOOGLE_ANALYTICS_4"."ENGAGEMENT_EVENTS_REPORT"'
  columns:
    DATE: DATE
    PROPERTY: VARCHAR(256)
    _FIVETRAN_ID: VARCHAR(256)
    EVENT_NAME: VARCHAR(256)
    TOTAL_USERS: DECIMAL(38, 0)
    EVENT_COUNT_PER_USER: FLOAT
    EVENT_COUNT: DECIMAL(38, 0)
    TOTAL_REVENUE: DECIMAL(38, 0)
    _FIVETRAN_SYNCED: TIMESTAMPTZ(9)
- name: '"RAW"."LOANS"."PERSONAL_LOANS"'
  columns:
    _AIRBYTE_RAW_ID: VARCHAR(16777216)
    _AIRBYTE_EXTRACTED_AT: TIMESTAMPTZ(9)
    _AIRBYTE_META: VARIANT
    TOTAL_ACC: FLOAT
    ANNUAL_INC: FLOAT
    EMP_LENGTH: VARCHAR(16777216)
    DESC: VARCHAR(16777216)
    TOTAL_PYMNT: FLOAT
    LAST_PYMNT_D: VARCHAR(16777216)
    ADDR_STATE: VARCHAR(16777216)
    NEXT_PYMNT_D: VARCHAR(16777216)
    EMP_TITLE: VARCHAR(16777216)
    COLLECTION_RECOVERY_FEE: FLOAT
    MTHS_SINCE_LAST_MAJOR_DEROG: FLOAT
    INQ_LAST_6MTHS: FLOAT
    SUB_GRADE: VARCHAR(16777216)
    FUNDED_AMNT_INV: FLOAT
    DELINQ_2YRS: FLOAT
    LOAN_ID: VARCHAR(16777216)
    FUNDED_AMNT: FLOAT
    VERIFICATION_STATUS: VARCHAR(16777216)
    DTI: FLOAT
    TOTAL_REC_PRNCP: FLOAT
    GRADE: VARCHAR(16777216)
    HOME_OWNERSHIP: VARCHAR(16777216)
    ISSUE_D: VARCHAR(16777216)
    MTHS_SINCE_LAST_DELINQ: FLOAT
    OUT_PRNCP: FLOAT
    PUB_REC: FLOAT
    INT_RATE: FLOAT
    ZIP_CODE: VARCHAR(16777216)
    OPEN_ACC: FLOAT
    TERM: VARCHAR(16777216)
    PYMNT_PLAN: VARCHAR(16777216)
    URL: VARCHAR(16777216)
    REVOL_BAL: FLOAT
    RECOVERIES: FLOAT
    LAST_PYMNT_AMNT: FLOAT
    LOAN_AMNT: FLOAT
    PURPOSE: VARCHAR(16777216)
    INITIAL_LIST_STATUS: VARCHAR(16777216)
    TOTAL_REC_INT: FLOAT
    TOTAL_PYMNT_INV: FLOAT
    MTHS_SINCE_LAST_RECORD: FLOAT
    LAST_CREDIT_PULL_D: VARCHAR(16777216)
    TOTAL_REC_LATE_FEE: FLOAT
    MEMBER_ID: FLOAT
    POLICY_CODE: FLOAT
    TITLE: VARCHAR(16777216)
    LOAN_STATUS: VARCHAR(16777216)
    INSTALLMENT: FLOAT
    EARLIEST_CR_LINE: VARCHAR(16777216)
    REVOL_UTIL: VARCHAR(16777216)
    OUT_PRNCP_INV: FLOAT
    COLLECTIONS_12_MTHS_EX_MED: FLOAT
- name: '"RAW"."RAW"."COUNTRY_POPULATIONS"'
  columns:
    _AIRBYTE_RAW_ID: VARCHAR(16777216)
    _AIRBYTE_EXTRACTED_AT: TIMESTAMPTZ(9)
    _AIRBYTE_META: VARIANT
    YEAR: FLOAT
    COUNTRY NAME: VARCHAR(16777216)
    VALUE: FLOAT
    COUNTRY CODE: VARCHAR(16777216)
- name: '"RAW"."US_POPULATION"."US_POPULATION"'
  columns:
    STATES: VARCHAR(16777216)
    ID: DECIMAL(19, 0)
    _2010: VARCHAR(16777216)
    _2011: VARCHAR(16777216)
    _2012: VARCHAR(16777216)
    _2013: VARCHAR(16777216)
    _2014: VARCHAR(16777216)
    _2015: VARCHAR(16777216)
    _2016: VARCHAR(16777216)
    _2017: VARCHAR(16777216)
    _2018: VARCHAR(16777216)
    _2019: VARCHAR(16777216)
- name: '"SNOWFLAKE"."ACCOUNT_USAGE"."PIPE_USAGE_HISTORY"'
  columns:
    PIPE_ID: DECIMAL(38, 0)
    PIPE_NAME: VARCHAR(16777216)
    START_TIME: TIMESTAMPLTZ(0)
    END_TIME: TIMESTAMPLTZ(9)
    CREDITS_USED: DECIMAL(38, 9)
    BYTES_INSERTED: FLOAT
    FILES_INSERTED: VARIANT
- name: '"SNOWFLAKE"."ACCOUNT_USAGE"."QUERY_HISTORY"'
  columns:
    QUERY_ID: VARCHAR(16777216)
    QUERY_TEXT: VARCHAR(16777216)
    DATABASE_ID: DECIMAL(38, 0)
    DATABASE_NAME: VARCHAR(16777216)
    SCHEMA_ID: DECIMAL(38, 0)
    SCHEMA_NAME: VARCHAR(16777216)
    QUERY_TYPE: VARCHAR(16777216)
    SESSION_ID: DECIMAL(38, 0)
    USER_NAME: VARCHAR(16777216)
    ROLE_NAME: VARCHAR(16777216)
    WAREHOUSE_ID: DECIMAL(38, 0)
    WAREHOUSE_NAME: VARCHAR(16777216)
    WAREHOUSE_SIZE: VARCHAR(16777216)
    WAREHOUSE_TYPE: VARCHAR(16777216)
    CLUSTER_NUMBER: DECIMAL(38, 0)
    QUERY_TAG: VARCHAR(16777216)
    EXECUTION_STATUS: VARCHAR(16777216)
    ERROR_CODE: VARCHAR(16777216)
    ERROR_MESSAGE: VARCHAR(16777216)
    START_TIME: TIMESTAMPLTZ(6)
    END_TIME: TIMESTAMPLTZ(6)
    TOTAL_ELAPSED_TIME: DECIMAL(38, 0)
    BYTES_SCANNED: DECIMAL(38, 0)
    PERCENTAGE_SCANNED_FROM_CACHE: FLOAT
    BYTES_WRITTEN: DECIMAL(38, 0)
    BYTES_WRITTEN_TO_RESULT: DECIMAL(38, 0)
    BYTES_READ_FROM_RESULT: DECIMAL(38, 0)
    ROWS_PRODUCED: DECIMAL(38, 0)
    ROWS_INSERTED: DECIMAL(38, 0)
    ROWS_UPDATED: DECIMAL(38, 0)
    ROWS_DELETED: DECIMAL(38, 0)
    ROWS_UNLOADED: DECIMAL(38, 0)
    BYTES_DELETED: DECIMAL(38, 0)
    PARTITIONS_SCANNED: DECIMAL(38, 0)
    PARTITIONS_TOTAL: DECIMAL(38, 0)
    BYTES_SPILLED_TO_LOCAL_STORAGE: DECIMAL(38, 0)
    BYTES_SPILLED_TO_REMOTE_STORAGE: DECIMAL(38, 0)
    BYTES_SENT_OVER_THE_NETWORK: DECIMAL(38, 0)
    COMPILATION_TIME: DECIMAL(38, 0)
    EXECUTION_TIME: DECIMAL(38, 0)
    QUEUED_PROVISIONING_TIME: DECIMAL(38, 0)
    QUEUED_REPAIR_TIME: DECIMAL(38, 0)
    QUEUED_OVERLOAD_TIME: DECIMAL(38, 0)
    TRANSACTION_BLOCKED_TIME: DECIMAL(38, 0)
    OUTBOUND_DATA_TRANSFER_CLOUD: VARCHAR(16777216)
    OUTBOUND_DATA_TRANSFER_REGION: VARCHAR(16777216)
    OUTBOUND_DATA_TRANSFER_BYTES: DECIMAL(38, 0)
    INBOUND_DATA_TRANSFER_CLOUD: VARCHAR(16777216)
    INBOUND_DATA_TRANSFER_REGION: VARCHAR(16777216)
    INBOUND_DATA_TRANSFER_BYTES: DECIMAL(38, 0)
    LIST_EXTERNAL_FILES_TIME: DECIMAL(38, 0)
    CREDITS_USED_CLOUD_SERVICES: FLOAT
    RELEASE_VERSION: VARCHAR(16777216)
    EXTERNAL_FUNCTION_TOTAL_INVOCATIONS: DECIMAL(38, 0)
    EXTERNAL_FUNCTION_TOTAL_SENT_ROWS: DECIMAL(38, 0)
    EXTERNAL_FUNCTION_TOTAL_RECEIVED_ROWS: DECIMAL(38, 0)
    EXTERNAL_FUNCTION_TOTAL_SENT_BYTES: DECIMAL(38, 0)
    EXTERNAL_FUNCTION_TOTAL_RECEIVED_BYTES: DECIMAL(38, 0)
    QUERY_LOAD_PERCENT: DECIMAL(38, 0)
    IS_CLIENT_GENERATED_STATEMENT: BOOLEAN
    QUERY_ACCELERATION_BYTES_SCANNED: DECIMAL(38, 0)
    QUERY_ACCELERATION_PARTITIONS_SCANNED: DECIMAL(38, 0)
    QUERY_ACCELERATION_UPPER_LIMIT_SCALE_FACTOR: DECIMAL(38, 0)
    TRANSACTION_ID: DECIMAL(38, 0)
    CHILD_QUERIES_WAIT_TIME: DECIMAL(38, 0)
    ROLE_TYPE: VARCHAR(16777216)
    QUERY_HASH: VARCHAR(16777216)
    QUERY_HASH_VERSION: DECIMAL(38, 0)
    QUERY_PARAMETERIZED_HASH: VARCHAR(16777216)
    QUERY_PARAMETERIZED_HASH_VERSION: DECIMAL(38, 0)
- name: '"SNOWFLAKE"."ACCOUNT_USAGE"."STORAGE_USAGE"'
  columns:
    USAGE_DATE: DATE
    STORAGE_BYTES: DECIMAL(38, 6)
    STAGE_BYTES: DECIMAL(38, 6)
    FAILSAFE_BYTES: DECIMAL(38, 6)
    HYBRID_TABLE_STORAGE_BYTES: DECIMAL(38, 6)
- name: '"SNOWFLAKE"."ACCOUNT_USAGE"."WAREHOUSE_METERING_HISTORY"'
  columns:
    START_TIME: TIMESTAMPLTZ(0)
    END_TIME: TIMESTAMPLTZ(0)
    WAREHOUSE_ID: DECIMAL(38, 0)
    WAREHOUSE_NAME: VARCHAR(16777216)
    CREDITS_USED: DECIMAL(38, 9)
    CREDITS_USED_COMPUTE: DECIMAL(38, 9)
    CREDITS_USED_CLOUD_SERVICES: DECIMAL(38, 9)
