name: Test, Check and Generate Docs

on:
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    name: Main CI
    runs-on: ubuntu-latest

    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DBT_TEST_DATABASE: ${{ secrets.DBT_TEST_DATABASE }}
      DBT_PROFILES_DIR: .config
      DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
      DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE }}
      DBT_SNOWFLAKE_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_WAREHOUSE }}
      INPUT_DBT_PROJECT_FOLDER: transform

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install dbt packages
        uses: datacoves/dbt-coves-action@v1
        with:
          dbt_project_folder: "transform"
          command: "dbt deps"

      - name: Load dbt seeds
        uses: datacoves/dbt-coves-action@v1
        with:
          command: "cd transform && dbt seed --full-refresh"

      - name: lint
        uses: datacoves/dbt-coves-action@v1
        with:
          command: "dbt-coves check --no-fix"
          
      - name: Run dbt build
        uses: datacoves/dbt-coves-action@v1
        with:
          command: "cd transform && dbt build"

      - name: generate docs
        uses: datacoves/dbt-coves-action@v1
        with:
          command: "dbt docs generate"

      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: target