name: Test and Check on Pull Request

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    name: Main CI
    runs-on: ubuntu-latest

    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DBT_DATABASE: ${{ secrets.DBT_DATABASE }}_${{ github.event.number }}
      DBT_PROFILES_DIR: /github/workspace/automate
      DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
      DBT_SNOWFLAKE_ROLE: ${{ secrets.DBT_SNOWFLAKE_ROLE }}
      DBT_SNOWFLAKE_WAREHOUSE: ${{ secrets.DBT_SNOWFLAKE_WAREHOUSE }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install dbt packages
        uses: datacoves/dbt-coves-action@v1
        with:
          dbt_project_folder: "transform"
          command: "dbt deps"

      - name: Run governance checks
        uses: datacoves/dbt-coves-action@v1
        with:
          dbt_project_folder: "transform"
          command: "dbt-coves check --no-fix"

      - name: Run dbt build
        uses: datacoves/dbt-coves-action@v1
        with:
          dbt_project_folder: "transform"
          command: "dbt build --defer --state logs --select state:modified+"
